Unexpected exception type thrown, expected: <com.sbi.epay.hazelcast.exception.HazelcastException> but was: <org.mockito.exceptions.misusing.PotentialStubbingProblem>
Expected :class com.sbi.epay.hazelcast.exception.HazelcastException
Actual   :class org.mockito.exceptions.misusing.PotentialStubbingProblem

    @Test
    void testAddDataToCache_NullPointerException() {
        CacheableEntity entity = CacheableEntity.builder().mapName(null).key(KEY).build();

        Exception exception = assertThrows(HazelcastException.class, () -> {
            hazelcastService.addDataToCache(entity, hazelcastInstance);
        });

        assertEquals(HazelcastConstants.HAZELCAST_1001_MSG, exception.getMessage());
    }
